<!-- Calendar Widget -->
<div class="widget" id="calendar-widget">
    <div class="widget-header">
        <h2><span class="material-icons-round">calendar_month</span> Calendário</h2>
        <div class="calendar-controls">
            <button id="cal-today-btn" class="icon-btn" aria-label="Hoje" title="Hoje"><span class="material-icons-round">today</span></button>
            <button id="cal-prev" class="icon-btn"><span class="material-icons-round">chevron_left</span></button>
            <span id="cal-month-year" style="font-weight: 500;"></span>
            <button id="cal-next" class="icon-btn"><span class="material-icons-round">chevron_right</span></button>
        </div>
    </div>
    <div class="widget-content">
        <div class="calendar-grid">
            <div class="cal-day-name">Dom</div>
            <div class="cal-day-name">Seg</div>
            <div class="cal-day-name">Ter</div>
            <div class="cal-day-name">Qua</div>
            <div class="cal-day-name">Qui</div>
            <div class="cal-day-name">Sex</div>
            <div class="cal-day-name">Sáb</div>
            <!-- Days will be generated by JS -->
            <div id="cal-days-container" style="display: contents;"></div>
        </div>
    </div>
</div>
