<!-- Calendar Widget -->
<div class="widget" id="calendar-widget">
    <div class="widget-header">
        <h2><span class="material-icons-round">calendar_month</span> <?= i18n($user_lang, 'calendar') ?></h2>
        <div class="calendar-controls">
            <button id="cal-today-btn" class="icon-btn" aria-label="<?= i18n($user_lang, 'today') ?>" title="<?= i18n($user_lang, 'today') ?>"><span class="material-icons-round">today</span></button>
            <button id="cal-prev" class="icon-btn"><span class="material-icons-round">chevron_left</span></button>
            <span id="cal-month-year" style="font-weight: 500;"></span>
            <button id="cal-next" class="icon-btn"><span class="material-icons-round">chevron_right</span></button>
        </div>
    </div>
    <div class="widget-content">
        <div class="calendar-grid">
            <div class="cal-day-name"><?= i18n($user_lang, 'week_sun') ?></div>
            <div class="cal-day-name"><?= i18n($user_lang, 'week_mon') ?></div>
            <div class="cal-day-name"><?= i18n($user_lang, 'week_tue') ?></div>
            <div class="cal-day-name"><?= i18n($user_lang, 'week_wed') ?></div>
            <div class="cal-day-name"><?= i18n($user_lang, 'week_thu') ?></div>
            <div class="cal-day-name"><?= i18n($user_lang, 'week_fri') ?></div>
            <div class="cal-day-name"><?= i18n($user_lang, 'week_sat') ?></div>
            <!-- Days will be generated by JS -->
            <div id="cal-days-container" style="display: contents;"></div>
        </div>
    </div>
</div>
